In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd
import sqlalchemy
import folium
from folium import plugins
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

import datetime as dt

In [2]:
import folium
from folium.plugins import MarkerCluster
import pysal as ps
from pysal.viz import mapclassify

import ipywidgets as widgets

In [3]:
import partridge as ptg
idx = pd.IndexSlice

In [4]:
def positions_from_db(db_name, limit, offset=0, routes=['all']):
    cols = 'oid, trip_id, route_id, trip_start_time, trip_start_date, vehicle_id, occupancy_status, position_latitude, position_longitude, timestamp'
    aws_host='gtfs-rt-logging.clakglowlpps.us-west-2.rds.amazonaws.com'
    eng = sqlalchemy.create_engine(
        f'mysql://halfempty:tentoninety@{aws_host}:3306/{db_name}')
    
    where = ''
    sep = "'"
    
    if offset == 0:
        offset = ''
    else:
        offset = f'offset {offset}'
    if routes[0] != 'all':
        where = f"where route_id in {str(tuple(routes))} and weekday(timestamp) in (0,1,2,3,4)"
    else:
        where = 'where weekday(timestamp) in (0,1,2,3,4)'

    query = f'select {cols} from vehicle_positions {where} order by timestamp desc limit {limit} {offset}'
    print(query)
    df = pd.read_sql(query, con=eng)
    count = eng.execute('select count(*) from vehicle_positions').fetchall()[0][0]
    return df, count

In [5]:
def gdf_from_positions_df(df):
    
    df = df.dropna(subset=['position_latitude', 'position_longitude'])
    geo = gpd.points_from_xy(df['position_longitude'], df['position_latitude'])
    gdf = gpd.GeoDataFrame(df, geometry=geo, crs='EPSG:4326')
    
    return gdf

In [6]:
def feed_from_path(path):
    '''Using Partridge, read a (GeoPandas enabled) GTFS feed given a filepath'''
    _date, service_ids = ptg.read_busiest_date(path)
    
    view = {
        'trips.txt': {'service_id': service_ids},
    }
    return ptg.load_geo_feed(path, view)

In [7]:
mbta_gtfs = feed_from_path('./data/mbta/08282020_gtfs.zip')

In [8]:
def aggregate_by_stop(df, gtfs):
    
    routes = df['route_id'].unique()
    
    trips_crowding_rts = gtfs.trips[gtfs.trips['route_id'].isin(routes)]['trip_id']
    stops_crowding_routes = gtfs.stop_times[gtfs.stop_times['trip_id'].isin(trips_crowding_rts)].drop_duplicates(subset=['stop_id'])['stop_id']
    stops_with_crowding = gtfs.stops[gtfs.stops['stop_id'].isin(stops_crowding_routes)]
    stops_with_crowding = stops_with_crowding[['stop_id', 'stop_name', 'geometry']]

    #https://spatialreference.org/ref/epsg/3586/
    stops_projected = stops_with_crowding.to_crs('EPSG:3586')

    #250ft buffer
    stops_projected['geometry'] = stops_projected['geometry'].buffer(250)
#     return stops_projected

    df = df.to_crs('EPSG:3586')
    ##filter df smaller...
    try:
        df.drop(columns=['position_latitude',
                          'position_longitude'], inplace=True)
    except KeyError:
        pass

    join1 = gpd.sjoin(stops_projected, df, how='left', op='contains')
#     return join1
    join1['hour'] = join1['timestamp'].dt.hour
    grouped = join1.groupby(['stop_id', 'route_id', 'hour'])
    series = grouped['occupancy_status'].value_counts().transpose()
    testdf = (pd.DataFrame(series)
              .rename(columns={'occupancy_status':'reports'})
              .unstack(level=[3]))

    ##This is it!
    testdf = testdf.droplevel(0, axis=1)
    geo_df = stops_projected.set_index('stop_id')
    
    return testdf, geo_df

In [9]:
def agg_positions_with_crowding(db_name, gtfs):
    
    #fetch a subset and sense which routes provide crowding data
    subset_allrt, row_count = positions_from_db(db_name, 100000)
#     print(row_count)
#     return
    #routes where crowding info isn't all the same, i.e. actual data
    values_by_rt = subset_allrt.groupby('route_id')['occupancy_status'].nunique().eq(1)
    routes_with_crowding = values_by_rt[values_by_rt == False].index
    
    ##TODO too small for MBTA but need memory for gtfs stops, implement batching every 10**6 on final.
    i = 0
    while i < row_count:
        gdf_crowding, _count = positions_from_db(db_name, 5*10**5, 
                                         offset=i, routes=routes_with_crowding)
        if gdf_crowding.shape[0] == 0:
            break
        gdf_crowding = gdf_from_positions_df(gdf_crowding)
        aggregated_df, geo_df = aggregate_by_stop(gdf_crowding, gtfs)
        if i == 0:
            global db1
            db1 = aggregated_df
            aggregated_dfs = aggregated_df
        else:
            global db2
            db2 = aggregated_df
            aggregated_dfs = aggregated_dfs.add(aggregated_df, fill_value=0)
        i += 5*10**5
    return aggregated_dfs, geo_df

In [10]:
# mbta, mbta_geo = agg_positions_with_crowding('mbta', mbta_gtfs)

In [11]:
def in_stop_list(x):
    try:
        test_list = list(stops_per_rt.loc[x['route_id'].iloc[0]])
    except:
        print(f"no stop data for route {x['route_id'].iloc[0]}!")
        return
    return x[x['stop_id'].isin(test_list)]

In [12]:
def filter_actual_stops(df, gtfs):
    
    def in_stop_list(x):
        try:
            test_list = list(stops_per_rt.loc[x['route_id'].iloc[0]])
        except:
            print(f"no stop data for route {x['route_id'].iloc[0]}!")
            return
        return x[x['stop_id'].isin(test_list)]

    trip_indexed = gtfs.trips.set_index('trip_id')[['route_id', 'direction_id']]
    stops_per_rt = gtfs.stop_times.set_index('trip_id').join(trip_indexed).groupby('route_id')['stop_id'].unique()
#     return stops_per_rt
    reset = df.reset_index()
    rt_group = reset.groupby('route_id')
    df = rt_group.apply(in_stop_list)
#     return df
    df = df.set_index('stop_id', append=True).set_index('hour', append=True).droplevel(1)
    
    return df

In [67]:
mbta.reset_index()

occupancy_status,stop_id,route_id,hour,EMPTY,FEW_SEATS_AVAILABLE,FULL,MANY_SEATS_AVAILABLE
0,1,1,0.0,20.0,6.0,NaN,42.0
1,1,1,1.0,21.0,2.0,NaN,34.0
2,1,1,2.0,19.0,NaN,NaN,33.0
3,1,1,3.0,9.0,NaN,NaN,33.0
4,1,1,4.0,11.0,2.0,NaN,26.0
...,...,...,...,...,...,...,...
282048,99991,Shuttle-Generic,12.0,1.0,NaN,NaN,NaN
282049,99991,Shuttle-Generic,13.0,1.0,NaN,NaN,NaN
282050,99991,Shuttle-Generic,16.0,2.0,NaN,NaN,NaN
282051,99991,Shuttle-Generic,18.0,1.0,NaN,NaN,NaN
282052,99991,Shuttle-Generic,22.0,1.0,NaN,NaN,NaN

In [68]:
mbta_filtered = filter_actual_stops(mbta, mbta_gtfs)

no stop data for route 62!
no stop data for route Shuttle-Generic!
no stop data for route Shuttle-Generic-Red!

In [69]:
mbta_filtered.loc[idx['1',:,:],:].index.get_level_values(1).unique()

Index(['1', '10003', '101', '10100', '10101', '102', '104', '10590', '106',
       '107', '108', '109', '110', '187', '188', '2', '57', '58', '59', '6',
       '62', '63', '64', '66', '67', '68', '69', '71', '72', '73', '74', '75',
       '77', '79', '80', '82', '83', '84', '854', '856', '87', '88', '89',
       '91', '93', '95', '97', '99'],
      dtype='object', name='stop_id')

In [70]:
mbta_filtered.to_parquet('./data/mbta/mbta_filtered.parquet')

In [71]:
##approx Aug 17 to Sep 4... 
##TODO implement timestamping in df fetch, or from S3 files...

In [13]:
mbta_filtered = pd.read_parquet('./data/mbta/mbta_filtered.parquet')

In [14]:
mbta_filtered

occupancy_status      route_id  EMPTY  FEW_SEATS_AVAILABLE  FULL  \
route_id stop_id hour
1        1       0.0         1   20.0                  6.0   NaN
                 1.0         1   21.0                  2.0   NaN
                 2.0         1   19.0                  NaN   NaN
                 3.0         1    9.0                  NaN   NaN
                 4.0         1   11.0                  2.0   NaN
...                        ...    ...                  ...   ...
94       63241   19.0       94   24.0                  NaN   NaN
                 20.0       94   11.0                  NaN   NaN
                 21.0       94    9.0                  NaN   NaN
                 22.0       94   11.0                  NaN   NaN
                 23.0       94    8.0                  NaN   NaN

occupancy_status       MANY_SEATS_AVAILABLE
route_id stop_id hour
1        1       0.0                   42.0
                 1.0                   34.0
                 2.0                   33.0
                 3.0                   33.0
                 4.0                   26.0
...                                     ...
94       63241   19.0                   NaN
                 20.0                   NaN
                 21.0                   1.0
                 22.0                   NaN
                 23.0                   2.0

[152546 rows x 5 columns]

In [75]:
mbta_geo.to_file('./data/mbta/mbta_geo.geojson', driver="GeoJSON")

In [15]:
mbta_geo = gpd.read_file('./data/mbta/mbta_geo.geojson').set_index('stop_id', drop=True)

### next: 
   * view logic, calculate metric
   * visualizer

In [16]:
def crowding_view(df, geo_df, st_hour, end_hour, routes='all'):
    if routes != 'all':
        ##TODO this might not be right...
        df = df.loc[idx[routes,:,np.arange(st_hour, end_hour)],:]
#         return df
        df = df.groupby('stop_id').sum()
    else:
        df = df.loc[idx[:,:,st_hour:end_hour,:]].groupby('stop_id').sum()

    df['Total Observations'] = df.sum(axis=1)
    df['Percent Full'] = (df['FULL'] / df['Total Observations']) * 100
    df['Percent Full/Few Available'] = (((df['FEW_SEATS_AVAILABLE'] / df['Total Observations']) * 100)
                                        .add(df['Percent Full'], fill_value=0))
    return geo_df.join(df).dropna(subset=['Percent Full/Few Available']).to_crs('EPSG:4326')

In [17]:
twenty_rts = list(mbta_filtered.index.get_level_values('route_id').unique())[:20]

In [18]:
viewdf = crowding_view(mbta_filtered, mbta_geo, st_hour=0, end_hour=20, routes=['1'])

In [19]:
viewdf

,stop_name,geometry,EMPTY,FEW_SEATS_AVAILABLE,FULL,MANY_SEATS_AVAILABLE,Total Observations,Percent Full,Percent Full/Few Available
stop_id,,,,,,,,,
1,Washington St opp Ruggles St,"POLYGON ((-71.08183 42.33095, -71.08183 42.330...",358.0,101.0,17.0,692.0,1168.0,1.455479,10.102740
10003,Albany St opp Randall St,"POLYGON ((-71.07531 42.33159, -71.07532 42.331...",128.0,195.0,24.0,1041.0,1388.0,1.729107,15.778098
101,Massachusetts Ave @ Sidney St,"POLYGON ((-71.09856 42.36298, -71.09857 42.362...",82.0,192.0,15.0,1584.0,1873.0,0.800854,11.051789
10100,Albany St @ Randall St,"POLYGON ((-71.07542 42.33167, -71.07543 42.331...",136.0,220.0,25.0,1116.0,1497.0,1.670007,16.366065
10101,Melnea Cass Blvd @ Harrison Ave,"POLYGON ((-71.07822 42.33206, -71.07823 42.332...",196.0,238.0,28.0,1246.0,1708.0,1.639344,15.573770
102,Massachusetts Ave @ Prospect St,"POLYGON ((-71.10248 42.36529, -71.10248 42.365...",121.0,175.0,16.0,2284.0,2596.0,0.616333,7.357473
104,Massachusetts Ave @ Bigelow St,"POLYGON ((-71.10489 42.36678, -71.10489 42.366...",127.0,245.0,2.0,1573.0,1947.0,0.102722,12.686184
10590,Massachusetts Ave @ Washington St,"POLYGON ((-71.07603 42.33662, -71.07604 42.336...",278.0,669.0,88.0,1893.0,2928.0,3.005464,25.853825
106,Massachusetts Ave @ Hancock St,"POLYGON ((-71.10769 42.36839, -71.10770 42.368...",50.0,27.0,2.0,960.0,1039.0,0.192493,2.791145
107,Massachusetts Ave @ Dana St,"POLYGON ((-71.10985 42.36926, -71.10985 42.369...",54.0,15.0,1.0,793.0,863.0,0.115875,1.853998
108,Massachusetts Ave @ Trowbridge St,"POLYGON ((-71.11207 42.37027, -71.11208 42.370...",94.0,37.0,1.0,1451.0,1583.0,0.063171,2.400505
109,Massachusetts Ave @ Bow St,"POLYGON ((-71.11445 42.37210, -71.11445 42.372...",43.0,11.0,1.0,399.0,454.0,0.220264,2.643172
110,Massachusetts Ave @ Holyoke St,"POLYGON ((-71.11720 42.37326, -71.11720 42.373...",3426.0,157.0,17.0,8740.0,12340.0,0.137763,1.410049
187,Massachusetts Ave @ Massachusetts Ave Station,"POLYGON ((-71.08240 42.34155, -71.08241 42.341...",91.0,631.0,79.0,1695.0,2496.0,3.165064,28.445513
188,Massachusetts Ave @ Massachusetts Ave Station,"POLYGON ((-71.08217 42.34157, -71.08217 42.341...",92.0,654.0,78.0,1730.0,2554.0,3.054033,28.660924
2,Washington St @ Melnea Cass Blvd,"POLYGON ((-71.08033 42.33232, -71.08033 42.332...",508.0,310.0,42.0,1700.0,2560.0,1.640625,13.750000
57,Massachusetts Ave @ Albany St,"POLYGON ((-71.07262 42.33382, -71.07262 42.333...",227.0,654.0,78.0,2010.0,2969.0,2.627147,24.654766
58,Massachusetts Ave @ Harrison Ave,"POLYGON ((-71.07401 42.33494, -71.07401 42.334...",176.0,747.0,93.0,1851.0,2867.0,3.243809,29.298919
59,Massachusetts Ave @ Washington St,"POLYGON ((-71.07602 42.33629, -71.07602 42.336...",266.0,649.0,85.0,1856.0,2856.0,2.976190,25.700280
6,Melnea Cass Blvd @ Harrison Ave,"POLYGON ((-71.07865 42.33201, -71.07866 42.331...",185.0,227.0,26.0,1235.0,1673.0,1.554094,15.122534
62,Washington St @ Williams St,"POLYGON ((-71.08081 42.33204, -71.08082 42.331...",426.0,196.0,25.0,1001.0,1648.0,1.516990,13.410194
63,Washington St @ Ruggles St,"POLYGON ((-71.08195 42.33103, -71.08196 42.330...",358.0,101.0,17.0,691.0,1167.0,1.456727,10.111397
66,Mt Auburn St @ DeWolfe St,"POLYGON ((-71.11504 42.37092, -71.11505 42.370...",68.0,7.0,0.0,635.0,710.0,0.000000,0.985915
67,Mt Auburn St @ Putnam Ave,"POLYGON ((-71.11259 42.37004, -71.11259 42.369...",88.0,33.0,1.0,1420.0,1542.0,0.064851,2.204929
68,Massachusetts Ave @ Bay St,"POLYGON ((-71.10950 42.36895, -71.10951 42.368...",54.0,15.0,1.0,763.0,833.0,0.120048,1.920768
69,Massachusetts Ave @ Hancock St,"POLYGON ((-71.10801 42.36835, -71.10802 42.368...",57.0,27.0,2.0,945.0,1031.0,0.193986,2.812803
71,Massachusetts Ave opp Inman St,"POLYGON ((-71.10500 42.36660, -71.10500 42.366...",130.0,247.0,2.0,1588.0,1967.0,0.101678,12.658871
72,Massachusetts Ave @ Pearl St,"POLYGON ((-71.10215 42.36491, -71.10215 42.364...",114.0,172.0,16.0,2282.0,2584.0,0.619195,7.275542
73,Massachusetts Ave @ Sidney St,"POLYGON ((-71.09858 42.36280, -71.09859 42.362...",77.0,177.0,15.0,1551.0,1820.0,0.824176,10.549451
74,Massachusetts Ave @ Albany St,"POLYGON ((-71.09509 42.36070, -71.09509 42.360...",98.0,328.0,23.0,1998.0,2447.0,0.939926,14.344095
75,84 Massachusetts Ave,"POLYGON ((-71.09271 42.35894, -71.09271 42.358...",56.0,241.0,20.0,1107.0,1424.0,1.404494,18.328652
77,Massachusetts Ave @ Marlborough St,"POLYGON ((-71.08822 42.34995, -71.08823 42.349...",84.0,339.0,39.0,1668.0,2130.0,1.830986,17.746479
79,Massachusetts Ave @ Newbury St,"POLYGON ((-71.08722 42.34793, -71.08723 42.347...",102.0,482.0,51.0,2027.0,2662.0,1.915853,20.022539
80,Massachusetts Ave opp Christian Science Ctr,"POLYGON ((-71.08553 42.34436, -71.08554 42.344...",56.0,195.0,17.0,812.0,1080.0,1.574074,19.629630
82,Massachusetts Ave @ Huntington Ave,"POLYGON ((-71.08378 42.34247, -71.08378 42.342...",87.0,456.0,48.0,1554.0,2145.0,2.237762,23.496503
83,Massachusetts Ave @ Columbus Ave,"POLYGON ((-71.08102 42.34062, -71.08103 42.340...",173.0,746.0,114.0,1850.0,2883.0,3.954214,29.830038
84,Massachusetts Ave @ Tremont St,"POLYGON ((-71.07937 42.33907, -71.07938 42.339...",105.0,614.0,97.0,1498.0,2314.0,4.191876,30.726016
854,Massachusetts Ave @ Harrison Ave,"POLYGON ((-71.07419 42.33474, -71.07419 42.334...",172.0,740.0,93.0,1813.0,2818.0,3.300213,29.559972
856,Massachusetts Ave @ Albany St,"POLYGON ((-71.07276 42.33354, -71.07277 42.333...",252.0,689.0,85.0,2188.0,3214.0,2.644680,24.082141
87,Massachusetts Ave @ Tremont St,"POLYGON ((-71.07944 42.33946, -71.07944 42.339...",93.0,591.0,91.0,1470.0,2245.0,4.053452,30.378619
88,Massachusetts Ave @ Columbus Ave,"POLYGON ((-71.08069 42.34060, -71.08070 42.340...",186.0,726.0,121.0,1868.0,2901.0,4.170976,29.196829
89,Massachusetts Ave @ St Botolph St,"POLYGON ((-71.08320 42.34230, -71.08320 42.342...",86.0,479.0,53.0,1513.0,2131.0,2.487095,24.964805
91,Massachusetts Ave @ Clearway St,"POLYGON ((-71.08581 42.34533, -71.08582 42.345...",35.0,165.0,25.0,721.0,946.0,2.642706,20.084567
93,Massachusetts Ave @ Newbury St,"POLYGON ((-71.08711 42.34800, -71.08711 42.347...",105.0,497.0,51.0,2081.0,2734.0,1.865399,20.043892
95,Massachusetts Ave @ Beacon St,"POLYGON ((-71.08841 42.35077, -71.08841 42.350...",65.0,225.0,29.0,1226.0,1545.0,1.877023,16.440129
97,77 Massachusetts Ave,"POLYGON ((-71.09262 42.35918, -71.09262 42.359...",47.0,227.0,23.0,1031.0,1328.0,1.731928,18.825301
99,Massachusetts Ave @ Albany St,"POLYGON ((-71.09480 42.36075, -71.09480 42.360...",107.0,332.0,23.0,2133.0,2595.0,0.886320,13.680154
64,Nubian,"POLYGON ((-71.08296 42.32979, -71.08297 42.329...",8114.0,568.0,49.0,7316.0,16047.0,0.305353,3.844955

In [81]:
#nbi:hide_in
def add_choropleth(gdf, m, classifier):
    
    gdf = gdf.dropna(subset=['Percent Full/Few Available'])
    gdf['Percent Full/Few Available'] = gdf['Percent Full/Few Available'].round(2)
    gdf.rename(columns={'stop_name':'Stop Name'},inplace=True)
    gdf.rename_axis('Stop ID', inplace=True)
    if classifier == 'Fixed':
#         threshold_scale = [0, 0.2, 0.4, 0.6, 0.8, 1.0, 1.2, 2.0]
        threshold_scale = [0, 20, 40, 60, 80, 101]
    elif classifier == 'Quantiles':
        threshold_scale = mapclassify.Quantiles(
            gdf['Percent Full/Few Available'], k = 5).bins.tolist()
        threshold_scale = [gdf['Percent Full/Few Available'].min()] + threshold_scale
        print(threshold_scale)
    elif classifier == 'Natural Breaks':
        threshold_scale = mapclassify.NaturalBreaks(
            gdf['Percent Full/Few Available'], k = 5).bins.tolist()
        threshold_scale = [gdf['Percent Full/Few Available'].min()] + threshold_scale
#     print(threshold_scale)
    choropleth = folium.Choropleth(geo_data = gdf.reset_index().to_json(),
                                   data = gdf.reset_index(),
                    columns = ('Stop ID', 'Percent Full/Few Available'), key_on = 'feature.properties.Stop ID',
                    nan_fill_color = 'red', fill_color = 'YlOrRd', fill_opacity = 0.6, line_opacity = 0.2,  
                    threshold_scale = threshold_scale, legend_name='Percentage of Service either Few Seats or Full'
                                    )
    choropleth.add_to(m)
    
    choropleth.geojson.add_child(folium.features.GeoJsonTooltip(['Stop ID', 'Stop Name', 'Percent Full/Few Available']))
        
    return

In [82]:
routes = tuple(mbta_filtered.index.get_level_values('route_id').unique())

In [83]:
#nbi:hide_in
def interactive_map(hour_range, routes, classifier, df=mbta_filtered, geo_df=mbta_geo):
    print('Running data query...', end='')

    view = crowding_view(df, geo_df, hour_range[0], hour_range[1], routes)
    if view.shape[0] > 1000:
        print('Selection too large! Please select fewer routes.')
        return
    x = view['geometry'][0].centroid.x
    y = view['geometry'][0].centroid.y
    m = folium.Map([y, x], zoom_start = 13, tiles='Stamen Terrain')
    add_choropleth(view, m, classifier)
    print(' Done!')
    print('Drawing map...')
    print(view.shape)
    display(m)

In [84]:
options = range(0,25)
hours_widget = widgets.SelectionRangeSlider(
    options=options,
    index=(0,24),
    description='Hour Range',
    disabled=False
)

In [85]:
routes_widget = widgets.SelectMultiple(
    options=routes,
    value=[routes[0]],
    #rows=10,
    description='Routes',
    disabled=False
)

In [86]:
#nbi:hide_in
classify_widget = widgets.RadioButtons(
    options=['Quantiles', 'Natural Breaks', 'Fixed'],
    value='Fixed', # Defaults to 'Fixed'
#    layout={'width': 'max-content'}, # If the items' names are long
    description='Classifier:',
    disabled=False
)

In [87]:
widgets.interact(interactive_map, hour_range=hours_widget,
                 routes=routes_widget, classifier=classify_widget,
                 df=widgets.fixed(mbta_filtered), geo_df=widgets.fixed(mbta_geo));

interactive(children=(SelectionRangeSlider(description='Hour Range', index=(0, 24), options=(0, 1, 2, 3, 4, 5,…